<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlMap [
		<!ELEMENT sqlMap (sql*)>
		<!ELEMENT sql (#PCDATA)>
		<!ATTLIST sql id  CDATA #REQUIRED>
		]>
<sqlMap>
	<sql id="QUERY_ID_TEST1">
		<![CDATA[select a.userCode,a.uintCode,b.projectID,
				b.name as projectName,b.projectType,b.totalPoeples
				from projectInfo b join projectOwner a  on a.projectID=b.projectID
				 [companyType | join CompanyInfo c on b.companyId=c.companyId]
				where 1=1 {projectOwner:a,projectInfo:b}
				[projectType:pt| and b.projectType=:pt]
				[:companyType,:companyName | and
				 	 c.companyType=:companyType and c.companyName like :companyName]
				 order by b.name ]]>
	</sql>

	<sql id="LIST_ALL_USER">
		<![CDATA[
            select USERCODE as userCode, USERPIN as userPin , ISVALID as isValid, USERTYPE as userType,
                LOGINNAME as loginName, USERNAMEas userName, ENGLISHNAME as englishName, USERDESC as userDesc,
                LOGINTIMES as loginTimes, ACTIVETIME as activeTime, PWDEXPIREDTIME as pwdExpiredTime, LOGINIP as loginIp,
                ADDRBOOKID as addrbookId, REGEMAIL as regEmail ,  REGCELLPHONE as regCellPhone, USERWORD as userWord,
                USERTAG as userTag, USERORDER as userOrder, PRIMARYUNIT as primaryUnit
            from F_USERINFO
        ]]>
	</sql>

	<sql id="UPDATE_USER_PASSWORD">
		<![CDATA[ update F_USERINFO set USERPIN = ? where USERCODE = ? ]]>
	</sql>

	<sql id="LIST_ALL_OPTINFO">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_OPTMETHOD">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_ROLEINFO">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_ROLEPOWER">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_USERROLE">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_UNITINFO">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_USERUNIT">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_DATACATALOG">
		<![CDATA[  ]]>
	</sql>

	<sql id="LIST_ALL_DICTIONARY">
		<![CDATA[  ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_USERINFO">
		<![CDATA[
            select USER_CODE, USER_NAME , PRIMARY_UNIT, USER_ORDER
            from F_USERINFO where ISVALID='T' order by USER_ORDER
        ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_UNITINFO">
		<![CDATA[
            select UNIT_CODE, PARENT_UNIT, UNIT_NAME,
                   UNIT_MANAGER, UNIT_ORDER, UNIT_PATH
            from F_UNITINFO where ISVALID='T' order by UNIT_ORDER
        ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_USERUNIT">
		<![CDATA[
            select UNIT_CODE, USER_CODE,
                   USER_STATION, USER_RANK,
                   IS_PRIMARY as isPrimary, USER_ORDER as userOrder
            from F_USERUNIT
        ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_USERROLE">
		<![CDATA[
            select USER_CODE, ROLE_CODE,
            'D' as OBTAIN_TYPE, '' as inherited_From
            from F_USERROLE
        ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_RANK_INFO">
		<![CDATA[
            select DATA_CODE as RANK_CODE, DATA_VALUE as RANK_NAME, EXTRA_CODE as RANK
            from F_DATADICTIONARY where CATALOG_CODE = 'RankType'
        ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_STATION_INFO">
		<![CDATA[
            select DATA_CODE as STATION_CODE, DATA_VALUE as STATION_NAME
            from F_DATADICTIONARY where CATALOG_CODE = 'StationType'
        ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_ITEM_ROLE">
		<![CDATA[
            select DATA_CODE as RANK_CODE, EXTRA_CODE as RANK
            from F_DATADICTIONARY where CATALOG_CODE = 'FlowUserRole'
        ]]>
	</sql>

	<sql id="WORKFLOW_EXTERNAL_ROLE_INFO">
		<![CDATA[
            select ROLE_CODE, ROLE_NAME
            from F_ROLEINFO where IS_VALID = 'T'
        ]]>
	</sql>
</sqlMap>
